id: a2f2edd4-12db-4126-9c36-094dc27412e1
title: Disable Targeting DOF
subtitle:
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: 'theboy181, OldManKain, StevenssND', link: 'https://linktr.ee/theboy181' }

