id: 62ba7b3a-052e-457e-9424-bcf57ce75171
title: UI Blackscreen Fix
subtitle:
description:
version: 1.0.2
category: 1
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author: 
  - { name: 'MarethyuX', link: 'https://www.reddit.com/user/MarethyuX/'  }
  - { name: 'Dziggy', link: 'https://gamebanana.com/mods/450147#H1_4' }
  - { name: 'Shifthyamardillo', link: 'https://www.reddit.com/user/ShiftyArmadillo' }