id: 32c8d8fa-cb48-47ba-9295-77a12ec8d589
title: Increase Camera Speed
subtitle:
description:
version: 1.0.1
category: 2
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
author:
  - { name: 'theboy181, StevenssND', link: 'https://linktr.ee/theboy181' }

