---
id: 137ba435-d6e0-41da-ba20-13685baf6471
title: "Playstation UI Mod V11.5 - Normal - White"
subtitle: Normal layout, like default Nintendo layout, only icons replaced, with white Playstation icons.
description: "Contains Blackscreenfix, disable other instances of blackscreenfix, or this mod wont work"
version: 11.5.1
category: 3
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.2.0
    - 1.1.2
    - 1.1.1
    - 1.1.0
emulator:
  - 1
  - 2
compatibility:
  whitelist:
  blacklist:
  - 62ba7b3a-052e-457e-9424-bcf57ce75171
author:   
  - { name: Alerion921, link: https://gamebanana.com/mods/447721 }